<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Budget.Application\Budget.Application.csproj" />
    <ProjectReference Include="..\Budget.Infrastructure\Budget.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Blobs" Version="1.5.4" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <UserSecretsId>f8c3d518-3d98-4562-8032-d8386bfab42b</UserSecretsId>
  </PropertyGroup>

</Project>
